//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/playerControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerControls: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""playerControls"",
    ""maps"": [
        {
            ""name"": ""Hover"",
            ""id"": ""94043d19-ade5-4443-b772-49bd8752f3d6"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""c752966e-63ef-4e78-a8f5-6e172ef36e58"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": ""StickDeadzone(min=0.25)"",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""HoverHeightUp"",
                    ""type"": ""Button"",
                    ""id"": ""fa26c0eb-b02c-4cdd-9f6e-47bfd9e4de20"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""HoverHeightDown"",
                    ""type"": ""Button"",
                    ""id"": ""15cf642d-505c-43bd-9e5a-6098a11d5435"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Stop"",
                    ""type"": ""Button"",
                    ""id"": ""5bb3622d-e55d-4695-9a6d-fbac2bd73950"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Ignite"",
                    ""type"": ""Button"",
                    ""id"": ""24f2ecf8-b66e-4757-8a9c-e0287fad46fa"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""HoverHeightVector"",
                    ""type"": ""Value"",
                    ""id"": ""b241bce1-ff00-4cfe-8214-3779840d42b5"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Fire"",
                    ""type"": ""Value"",
                    ""id"": ""bf411e5a-2ed7-4e36-b9af-e6c1a147cc2c"",
                    ""expectedControlType"": ""Digital"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""YawVector"",
                    ""type"": ""Value"",
                    ""id"": ""4d6dae77-b55f-48ec-a719-8abbcc86ee4b"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": ""AxisDeadzone(min=0.25)"",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Thrust"",
                    ""type"": ""Value"",
                    ""id"": ""c7175c48-228c-40c8-841e-bd19b6a6ee9b"",
                    ""expectedControlType"": ""Analog"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""SwitchMode"",
                    ""type"": ""Button"",
                    ""id"": ""f6ccc02c-af57-4fe5-98d7-8860c837d66a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RightStickY"",
                    ""type"": ""Value"",
                    ""id"": ""adcd14e4-7c14-4e64-aace-cd6d1bc77340"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""CycleCamera"",
                    ""type"": ""Button"",
                    ""id"": ""b88876d6-e741-4bba-9409-bd0558154449"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LandingGear"",
                    ""type"": ""Button"",
                    ""id"": ""4633b9b5-8160-475b-ace5-be939f76224d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CameraLook"",
                    ""type"": ""Value"",
                    ""id"": ""5906b94e-f834-46c1-b140-c045e5128bc3"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""ToggleMenu"",
                    ""type"": ""Button"",
                    ""id"": ""c9892cea-3a87-47a3-9fd2-fb0a4233a656"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""46fb6174-bf3f-44d2-8ec2-c4160d7d0c2e"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": ""StickDeadzone(min=0.25,max=0.925)"",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""WASD"",
                    ""id"": ""631c3d25-d46f-4abf-8d72-5eafbd7d1622"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""198391f5-db23-40e3-b25c-e0774114fdde"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""57a9bb05-a2ad-42da-b70b-cb22f8c07f75"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""9db15d47-6527-4374-9a46-7ff56b5c56c3"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""46944aeb-77a2-4e05-ac66-9c140010506a"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""73ecea94-207e-4dfd-953c-f4109bb4ec56"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HoverHeightUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d2c164d4-45b0-495a-a924-a754c5658607"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HoverHeightUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""35f032da-cb2e-433d-9d17-c24c3512f61c"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HoverHeightDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e4aacef7-5c45-4a7e-8038-ad1d30fa600e"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HoverHeightDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0a0d0b35-4950-403f-9686-d3a1618699c8"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Stop"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""80cef66a-5864-4499-b67d-a34978d73058"",
                    ""path"": ""<Gamepad>/leftStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Stop"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""502cffc0-4081-4470-94d6-85119c665c6d"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Ignite"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""86be0e98-8181-4bfe-8fc9-7cef460b3e1f"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Ignite"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""e7ee8ada-f46c-46cd-9309-4ee8c6de9100"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HoverHeightVector"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""ce1eaa34-68d5-432f-8993-1a0907ff6fe3"",
                    ""path"": ""<Gamepad>/rightStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HoverHeightVector"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""b5e6402e-bcf3-4df2-a4e0-773f8be357f6"",
                    ""path"": ""<Gamepad>/rightStick/y"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HoverHeightVector"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""9bd63f52-2af9-402b-8c41-545a2a0b1927"",
                    ""path"": ""1DAxis(whichSideWins=1)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HoverHeightVector"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""ead87a3a-be07-4c80-b9f2-23f42dd0b0d1"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HoverHeightVector"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""c8526e63-fa71-4751-b447-9c894f5b7d83"",
                    ""path"": ""<Keyboard>/leftCtrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HoverHeightVector"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""17bf24cc-9325-4382-9762-077c44f55b71"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Fire"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""22396e5e-bde5-4a29-8b83-a71753b0430d"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""YawVector"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""bd1cfc8b-a0a2-43e8-aadf-19d8843ea9c5"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""YawVector"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""21f2181f-32f6-4e77-bbf7-be996155d395"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""YawVector"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""4c9065c5-7982-43e6-a9f7-52d88a8e0f04"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""YawVector"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""bf8a9f01-07e8-438d-b805-e0fabdabc3aa"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""YawVector"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""f539b58f-443f-43d3-92f2-fec2ea41b003"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""YawVector"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""38a20039-ff1e-40bd-bd70-90297fbb7be5"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Thrust"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b2a9d491-88a2-4fd9-ac01-34618a18ebe6"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Thrust"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""844701f7-a6c6-4487-9cd0-df9805832c6c"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwitchMode"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d15b99ae-d28a-450d-9a7c-40b73e4c159b"",
                    ""path"": ""<Gamepad>/rightStick/y"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightStickY"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c5605807-c0c1-4ced-9f4b-82e49c2242fa"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CycleCamera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""411488b0-dc6c-4477-94f7-0d54e806cbbd"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LandingGear"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""72fb9ef8-9703-4f8e-95e5-0d4f7bff23aa"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CameraLook"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""dee622c1-71e9-45a5-83de-a8e93d81be08"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ToggleMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""00a89a9b-9ae0-4a0b-b37a-113e7eed7bfd"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ToggleMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Hover
        m_Hover = asset.FindActionMap("Hover", throwIfNotFound: true);
        m_Hover_Move = m_Hover.FindAction("Move", throwIfNotFound: true);
        m_Hover_HoverHeightUp = m_Hover.FindAction("HoverHeightUp", throwIfNotFound: true);
        m_Hover_HoverHeightDown = m_Hover.FindAction("HoverHeightDown", throwIfNotFound: true);
        m_Hover_Stop = m_Hover.FindAction("Stop", throwIfNotFound: true);
        m_Hover_Ignite = m_Hover.FindAction("Ignite", throwIfNotFound: true);
        m_Hover_HoverHeightVector = m_Hover.FindAction("HoverHeightVector", throwIfNotFound: true);
        m_Hover_Fire = m_Hover.FindAction("Fire", throwIfNotFound: true);
        m_Hover_YawVector = m_Hover.FindAction("YawVector", throwIfNotFound: true);
        m_Hover_Thrust = m_Hover.FindAction("Thrust", throwIfNotFound: true);
        m_Hover_SwitchMode = m_Hover.FindAction("SwitchMode", throwIfNotFound: true);
        m_Hover_RightStickY = m_Hover.FindAction("RightStickY", throwIfNotFound: true);
        m_Hover_CycleCamera = m_Hover.FindAction("CycleCamera", throwIfNotFound: true);
        m_Hover_LandingGear = m_Hover.FindAction("LandingGear", throwIfNotFound: true);
        m_Hover_CameraLook = m_Hover.FindAction("CameraLook", throwIfNotFound: true);
        m_Hover_ToggleMenu = m_Hover.FindAction("ToggleMenu", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Hover
    private readonly InputActionMap m_Hover;
    private List<IHoverActions> m_HoverActionsCallbackInterfaces = new List<IHoverActions>();
    private readonly InputAction m_Hover_Move;
    private readonly InputAction m_Hover_HoverHeightUp;
    private readonly InputAction m_Hover_HoverHeightDown;
    private readonly InputAction m_Hover_Stop;
    private readonly InputAction m_Hover_Ignite;
    private readonly InputAction m_Hover_HoverHeightVector;
    private readonly InputAction m_Hover_Fire;
    private readonly InputAction m_Hover_YawVector;
    private readonly InputAction m_Hover_Thrust;
    private readonly InputAction m_Hover_SwitchMode;
    private readonly InputAction m_Hover_RightStickY;
    private readonly InputAction m_Hover_CycleCamera;
    private readonly InputAction m_Hover_LandingGear;
    private readonly InputAction m_Hover_CameraLook;
    private readonly InputAction m_Hover_ToggleMenu;
    public struct HoverActions
    {
        private @PlayerControls m_Wrapper;
        public HoverActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_Hover_Move;
        public InputAction @HoverHeightUp => m_Wrapper.m_Hover_HoverHeightUp;
        public InputAction @HoverHeightDown => m_Wrapper.m_Hover_HoverHeightDown;
        public InputAction @Stop => m_Wrapper.m_Hover_Stop;
        public InputAction @Ignite => m_Wrapper.m_Hover_Ignite;
        public InputAction @HoverHeightVector => m_Wrapper.m_Hover_HoverHeightVector;
        public InputAction @Fire => m_Wrapper.m_Hover_Fire;
        public InputAction @YawVector => m_Wrapper.m_Hover_YawVector;
        public InputAction @Thrust => m_Wrapper.m_Hover_Thrust;
        public InputAction @SwitchMode => m_Wrapper.m_Hover_SwitchMode;
        public InputAction @RightStickY => m_Wrapper.m_Hover_RightStickY;
        public InputAction @CycleCamera => m_Wrapper.m_Hover_CycleCamera;
        public InputAction @LandingGear => m_Wrapper.m_Hover_LandingGear;
        public InputAction @CameraLook => m_Wrapper.m_Hover_CameraLook;
        public InputAction @ToggleMenu => m_Wrapper.m_Hover_ToggleMenu;
        public InputActionMap Get() { return m_Wrapper.m_Hover; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(HoverActions set) { return set.Get(); }
        public void AddCallbacks(IHoverActions instance)
        {
            if (instance == null || m_Wrapper.m_HoverActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_HoverActionsCallbackInterfaces.Add(instance);
            @Move.started += instance.OnMove;
            @Move.performed += instance.OnMove;
            @Move.canceled += instance.OnMove;
            @HoverHeightUp.started += instance.OnHoverHeightUp;
            @HoverHeightUp.performed += instance.OnHoverHeightUp;
            @HoverHeightUp.canceled += instance.OnHoverHeightUp;
            @HoverHeightDown.started += instance.OnHoverHeightDown;
            @HoverHeightDown.performed += instance.OnHoverHeightDown;
            @HoverHeightDown.canceled += instance.OnHoverHeightDown;
            @Stop.started += instance.OnStop;
            @Stop.performed += instance.OnStop;
            @Stop.canceled += instance.OnStop;
            @Ignite.started += instance.OnIgnite;
            @Ignite.performed += instance.OnIgnite;
            @Ignite.canceled += instance.OnIgnite;
            @HoverHeightVector.started += instance.OnHoverHeightVector;
            @HoverHeightVector.performed += instance.OnHoverHeightVector;
            @HoverHeightVector.canceled += instance.OnHoverHeightVector;
            @Fire.started += instance.OnFire;
            @Fire.performed += instance.OnFire;
            @Fire.canceled += instance.OnFire;
            @YawVector.started += instance.OnYawVector;
            @YawVector.performed += instance.OnYawVector;
            @YawVector.canceled += instance.OnYawVector;
            @Thrust.started += instance.OnThrust;
            @Thrust.performed += instance.OnThrust;
            @Thrust.canceled += instance.OnThrust;
            @SwitchMode.started += instance.OnSwitchMode;
            @SwitchMode.performed += instance.OnSwitchMode;
            @SwitchMode.canceled += instance.OnSwitchMode;
            @RightStickY.started += instance.OnRightStickY;
            @RightStickY.performed += instance.OnRightStickY;
            @RightStickY.canceled += instance.OnRightStickY;
            @CycleCamera.started += instance.OnCycleCamera;
            @CycleCamera.performed += instance.OnCycleCamera;
            @CycleCamera.canceled += instance.OnCycleCamera;
            @LandingGear.started += instance.OnLandingGear;
            @LandingGear.performed += instance.OnLandingGear;
            @LandingGear.canceled += instance.OnLandingGear;
            @CameraLook.started += instance.OnCameraLook;
            @CameraLook.performed += instance.OnCameraLook;
            @CameraLook.canceled += instance.OnCameraLook;
            @ToggleMenu.started += instance.OnToggleMenu;
            @ToggleMenu.performed += instance.OnToggleMenu;
            @ToggleMenu.canceled += instance.OnToggleMenu;
        }

        private void UnregisterCallbacks(IHoverActions instance)
        {
            @Move.started -= instance.OnMove;
            @Move.performed -= instance.OnMove;
            @Move.canceled -= instance.OnMove;
            @HoverHeightUp.started -= instance.OnHoverHeightUp;
            @HoverHeightUp.performed -= instance.OnHoverHeightUp;
            @HoverHeightUp.canceled -= instance.OnHoverHeightUp;
            @HoverHeightDown.started -= instance.OnHoverHeightDown;
            @HoverHeightDown.performed -= instance.OnHoverHeightDown;
            @HoverHeightDown.canceled -= instance.OnHoverHeightDown;
            @Stop.started -= instance.OnStop;
            @Stop.performed -= instance.OnStop;
            @Stop.canceled -= instance.OnStop;
            @Ignite.started -= instance.OnIgnite;
            @Ignite.performed -= instance.OnIgnite;
            @Ignite.canceled -= instance.OnIgnite;
            @HoverHeightVector.started -= instance.OnHoverHeightVector;
            @HoverHeightVector.performed -= instance.OnHoverHeightVector;
            @HoverHeightVector.canceled -= instance.OnHoverHeightVector;
            @Fire.started -= instance.OnFire;
            @Fire.performed -= instance.OnFire;
            @Fire.canceled -= instance.OnFire;
            @YawVector.started -= instance.OnYawVector;
            @YawVector.performed -= instance.OnYawVector;
            @YawVector.canceled -= instance.OnYawVector;
            @Thrust.started -= instance.OnThrust;
            @Thrust.performed -= instance.OnThrust;
            @Thrust.canceled -= instance.OnThrust;
            @SwitchMode.started -= instance.OnSwitchMode;
            @SwitchMode.performed -= instance.OnSwitchMode;
            @SwitchMode.canceled -= instance.OnSwitchMode;
            @RightStickY.started -= instance.OnRightStickY;
            @RightStickY.performed -= instance.OnRightStickY;
            @RightStickY.canceled -= instance.OnRightStickY;
            @CycleCamera.started -= instance.OnCycleCamera;
            @CycleCamera.performed -= instance.OnCycleCamera;
            @CycleCamera.canceled -= instance.OnCycleCamera;
            @LandingGear.started -= instance.OnLandingGear;
            @LandingGear.performed -= instance.OnLandingGear;
            @LandingGear.canceled -= instance.OnLandingGear;
            @CameraLook.started -= instance.OnCameraLook;
            @CameraLook.performed -= instance.OnCameraLook;
            @CameraLook.canceled -= instance.OnCameraLook;
            @ToggleMenu.started -= instance.OnToggleMenu;
            @ToggleMenu.performed -= instance.OnToggleMenu;
            @ToggleMenu.canceled -= instance.OnToggleMenu;
        }

        public void RemoveCallbacks(IHoverActions instance)
        {
            if (m_Wrapper.m_HoverActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IHoverActions instance)
        {
            foreach (var item in m_Wrapper.m_HoverActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_HoverActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public HoverActions @Hover => new HoverActions(this);
    public interface IHoverActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnHoverHeightUp(InputAction.CallbackContext context);
        void OnHoverHeightDown(InputAction.CallbackContext context);
        void OnStop(InputAction.CallbackContext context);
        void OnIgnite(InputAction.CallbackContext context);
        void OnHoverHeightVector(InputAction.CallbackContext context);
        void OnFire(InputAction.CallbackContext context);
        void OnYawVector(InputAction.CallbackContext context);
        void OnThrust(InputAction.CallbackContext context);
        void OnSwitchMode(InputAction.CallbackContext context);
        void OnRightStickY(InputAction.CallbackContext context);
        void OnCycleCamera(InputAction.CallbackContext context);
        void OnLandingGear(InputAction.CallbackContext context);
        void OnCameraLook(InputAction.CallbackContext context);
        void OnToggleMenu(InputAction.CallbackContext context);
    }
}
