//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/playerControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerControls: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""playerControls"",
    ""maps"": [
        {
            ""name"": ""Hover"",
            ""id"": ""94043d19-ade5-4443-b772-49bd8752f3d6"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""c752966e-63ef-4e78-a8f5-6e172ef36e58"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": ""StickDeadzone(min=0.25)"",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""hoverLock"",
                    ""type"": ""Button"",
                    ""id"": ""5bb3622d-e55d-4695-9a6d-fbac2bd73950"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Ignite"",
                    ""type"": ""Button"",
                    ""id"": ""24f2ecf8-b66e-4757-8a9c-e0287fad46fa"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""YawVector"",
                    ""type"": ""Value"",
                    ""id"": ""4d6dae77-b55f-48ec-a719-8abbcc86ee4b"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": ""AxisDeadzone(min=0.25)"",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Thrust"",
                    ""type"": ""Value"",
                    ""id"": ""c7175c48-228c-40c8-841e-bd19b6a6ee9b"",
                    ""expectedControlType"": ""Analog"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""CameraLook"",
                    ""type"": ""Value"",
                    ""id"": ""5906b94e-f834-46c1-b140-c045e5128bc3"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""ToggleMenu"",
                    ""type"": ""Button"",
                    ""id"": ""c9892cea-3a87-47a3-9fd2-fb0a4233a656"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Brakes"",
                    ""type"": ""Value"",
                    ""id"": ""65eda8f1-a42b-4b39-b020-a455d46a9cf0"",
                    ""expectedControlType"": ""Analog"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""46fb6174-bf3f-44d2-8ec2-c4160d7d0c2e"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": ""StickDeadzone(min=0.25,max=0.925)"",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""WASD"",
                    ""id"": ""631c3d25-d46f-4abf-8d72-5eafbd7d1622"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""198391f5-db23-40e3-b25c-e0774114fdde"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""57a9bb05-a2ad-42da-b70b-cb22f8c07f75"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""9db15d47-6527-4374-9a46-7ff56b5c56c3"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""46944aeb-77a2-4e05-ac66-9c140010506a"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""502cffc0-4081-4470-94d6-85119c665c6d"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Ignite"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""86be0e98-8181-4bfe-8fc9-7cef460b3e1f"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Ignite"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""22396e5e-bde5-4a29-8b83-a71753b0430d"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""YawVector"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""bd1cfc8b-a0a2-43e8-aadf-19d8843ea9c5"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""YawVector"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""21f2181f-32f6-4e77-bbf7-be996155d395"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""YawVector"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""4c9065c5-7982-43e6-a9f7-52d88a8e0f04"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""YawVector"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""bf8a9f01-07e8-438d-b805-e0fabdabc3aa"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""YawVector"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""f539b58f-443f-43d3-92f2-fec2ea41b003"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""YawVector"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""38a20039-ff1e-40bd-bd70-90297fbb7be5"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Thrust"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b2a9d491-88a2-4fd9-ac01-34618a18ebe6"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Thrust"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""72fb9ef8-9703-4f8e-95e5-0d4f7bff23aa"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CameraLook"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""302d07f1-7695-4a2a-b1ec-5087db3b23cf"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CameraLook"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""dee622c1-71e9-45a5-83de-a8e93d81be08"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ToggleMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""00a89a9b-9ae0-4a0b-b37a-113e7eed7bfd"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ToggleMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""903c9b54-ea3b-466f-ba4f-da89a5a370d7"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Brakes"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2c3c847e-f7b5-41af-ae9a-0ea6d49470e1"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": ""Hold"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Brakes"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""841e7096-77f2-4c88-ba21-5d108a62e10f"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""hoverLock"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c65a294a-e3a6-47c5-8c13-dad7ea0b837d"",
                    ""path"": ""<Keyboard>/capsLock"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""hoverLock"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Hover
        m_Hover = asset.FindActionMap("Hover", throwIfNotFound: true);
        m_Hover_Move = m_Hover.FindAction("Move", throwIfNotFound: true);
        m_Hover_hoverLock = m_Hover.FindAction("hoverLock", throwIfNotFound: true);
        m_Hover_Ignite = m_Hover.FindAction("Ignite", throwIfNotFound: true);
        m_Hover_YawVector = m_Hover.FindAction("YawVector", throwIfNotFound: true);
        m_Hover_Thrust = m_Hover.FindAction("Thrust", throwIfNotFound: true);
        m_Hover_CameraLook = m_Hover.FindAction("CameraLook", throwIfNotFound: true);
        m_Hover_ToggleMenu = m_Hover.FindAction("ToggleMenu", throwIfNotFound: true);
        m_Hover_Brakes = m_Hover.FindAction("Brakes", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Hover
    private readonly InputActionMap m_Hover;
    private List<IHoverActions> m_HoverActionsCallbackInterfaces = new List<IHoverActions>();
    private readonly InputAction m_Hover_Move;
    private readonly InputAction m_Hover_hoverLock;
    private readonly InputAction m_Hover_Ignite;
    private readonly InputAction m_Hover_YawVector;
    private readonly InputAction m_Hover_Thrust;
    private readonly InputAction m_Hover_CameraLook;
    private readonly InputAction m_Hover_ToggleMenu;
    private readonly InputAction m_Hover_Brakes;
    public struct HoverActions
    {
        private @PlayerControls m_Wrapper;
        public HoverActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_Hover_Move;
        public InputAction @hoverLock => m_Wrapper.m_Hover_hoverLock;
        public InputAction @Ignite => m_Wrapper.m_Hover_Ignite;
        public InputAction @YawVector => m_Wrapper.m_Hover_YawVector;
        public InputAction @Thrust => m_Wrapper.m_Hover_Thrust;
        public InputAction @CameraLook => m_Wrapper.m_Hover_CameraLook;
        public InputAction @ToggleMenu => m_Wrapper.m_Hover_ToggleMenu;
        public InputAction @Brakes => m_Wrapper.m_Hover_Brakes;
        public InputActionMap Get() { return m_Wrapper.m_Hover; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(HoverActions set) { return set.Get(); }
        public void AddCallbacks(IHoverActions instance)
        {
            if (instance == null || m_Wrapper.m_HoverActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_HoverActionsCallbackInterfaces.Add(instance);
            @Move.started += instance.OnMove;
            @Move.performed += instance.OnMove;
            @Move.canceled += instance.OnMove;
            @hoverLock.started += instance.OnHoverLock;
            @hoverLock.performed += instance.OnHoverLock;
            @hoverLock.canceled += instance.OnHoverLock;
            @Ignite.started += instance.OnIgnite;
            @Ignite.performed += instance.OnIgnite;
            @Ignite.canceled += instance.OnIgnite;
            @YawVector.started += instance.OnYawVector;
            @YawVector.performed += instance.OnYawVector;
            @YawVector.canceled += instance.OnYawVector;
            @Thrust.started += instance.OnThrust;
            @Thrust.performed += instance.OnThrust;
            @Thrust.canceled += instance.OnThrust;
            @CameraLook.started += instance.OnCameraLook;
            @CameraLook.performed += instance.OnCameraLook;
            @CameraLook.canceled += instance.OnCameraLook;
            @ToggleMenu.started += instance.OnToggleMenu;
            @ToggleMenu.performed += instance.OnToggleMenu;
            @ToggleMenu.canceled += instance.OnToggleMenu;
            @Brakes.started += instance.OnBrakes;
            @Brakes.performed += instance.OnBrakes;
            @Brakes.canceled += instance.OnBrakes;
        }

        private void UnregisterCallbacks(IHoverActions instance)
        {
            @Move.started -= instance.OnMove;
            @Move.performed -= instance.OnMove;
            @Move.canceled -= instance.OnMove;
            @hoverLock.started -= instance.OnHoverLock;
            @hoverLock.performed -= instance.OnHoverLock;
            @hoverLock.canceled -= instance.OnHoverLock;
            @Ignite.started -= instance.OnIgnite;
            @Ignite.performed -= instance.OnIgnite;
            @Ignite.canceled -= instance.OnIgnite;
            @YawVector.started -= instance.OnYawVector;
            @YawVector.performed -= instance.OnYawVector;
            @YawVector.canceled -= instance.OnYawVector;
            @Thrust.started -= instance.OnThrust;
            @Thrust.performed -= instance.OnThrust;
            @Thrust.canceled -= instance.OnThrust;
            @CameraLook.started -= instance.OnCameraLook;
            @CameraLook.performed -= instance.OnCameraLook;
            @CameraLook.canceled -= instance.OnCameraLook;
            @ToggleMenu.started -= instance.OnToggleMenu;
            @ToggleMenu.performed -= instance.OnToggleMenu;
            @ToggleMenu.canceled -= instance.OnToggleMenu;
            @Brakes.started -= instance.OnBrakes;
            @Brakes.performed -= instance.OnBrakes;
            @Brakes.canceled -= instance.OnBrakes;
        }

        public void RemoveCallbacks(IHoverActions instance)
        {
            if (m_Wrapper.m_HoverActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IHoverActions instance)
        {
            foreach (var item in m_Wrapper.m_HoverActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_HoverActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public HoverActions @Hover => new HoverActions(this);
    public interface IHoverActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnHoverLock(InputAction.CallbackContext context);
        void OnIgnite(InputAction.CallbackContext context);
        void OnYawVector(InputAction.CallbackContext context);
        void OnThrust(InputAction.CallbackContext context);
        void OnCameraLook(InputAction.CallbackContext context);
        void OnToggleMenu(InputAction.CallbackContext context);
        void OnBrakes(InputAction.CallbackContext context);
    }
}
